/*
Meteor.subscribe('posCategory');
Meteor.subscribe('posUnit');
Meteor.subscribe('posSubCategory');
Meteor.subscribe('posStaff');
Meteor.subscribe('posCustomer');
Meteor.subscribe('posProduct');
Meteor.subscribe('posSale');
Meteor.subscribe('posSaleDetail');
Meteor.subscribe('posPayment');
Meteor.subscribe('posPurchase');
Meteor.subscribe('posPurchaseDetail');
Meteor.subscribe('posSupplier');
Meteor.subscribe('posStock');
Meteor.subscribe('posExchangeRate');
Meteor.subscribe('posStockHistory');
Meteor.subscribe('posUserStaff');
Meteor.subscribe('images');
Meteor.subscribe('adjustment');*/
Meteor.subscribe('posOwedSale');
